package:
  name: flaapluc
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/jlenain/flaapluc.git
  
requirements:
  build:
    - python 2.7*
    - email
    - numpy 1.13*
    - scipy
    - astropy >=2.*
    - matplotlib >=2.*
    - ephem
    - setuptools
    - uncertainties

  run:
    - python 2.7*
    - email
    - numpy 1.13*
    - scipy
    - astropy >=2.*
    - matplotlib >=2.*
    - ephem
    - setuptools
    - uncertainties

about:
  home: https://github.com/jlenain/flaapluc
  license: BSD
  license_file: LICENSE
