package:
  name: flaapluc
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/jlenain/flaapluc.git
  
requirements:
  build:
    - python 2.7.*
    - numpy 1.13.*
    - scipy 1.2.*
    - astropy 2.0.*
    - matplotlib 2.2.*
    - ephem 3.7.*
    - pytz 2020.*

  run:
    - python 2.7.*
    - numpy 1.13.*
    - scipy 1.2.*
    - astropy 2.0.*
    - matplotlib 2.2.*
    - ephem 3.7.*

about:
  home: https://github.com/jlenain/flaapluc
  license: BSD
  license_file: LICENSE
